erDiagram
    users {
        string id PK
        string email
        string password_hash
        string* user_role
        bool active 
    }

    clients {
        string id PK
        string name
    }

    apps {
        string id PK
        string name
    }

    client_apps {
        string id PK
        string app_id FK
        bool active
        string client_id FK
    }

    sessions {
        string id PK
        timestamptz expires_at
        string user_id FK
    }

    api_keys {
        string id PK
        string client_app_id FK
        string api_key_hash
        bool active
    }

    users ||--o{ sessions : ""
    clients ||--o{ client_apps : ""
    apps ||--o{ client_apps : ""
    client_apps ||--o{ api_keys : ""